In [6]:
import numpy as np

array = np.array([1,2,3,4,5,6,7])
print(array)

[1 2 3 4 5 6 7]


In [7]:
def get_greatest_common_divisor(in0: int, in1: int) -> int:
    if in0 <= in1:
        min_num = in0
        max_num = in1
    else:
        min_num = in1
        max_num = in0
    greatest_common_divisor = 1
    for i in range(1, min_num+1):
        if (min_num % i == 0) & (max_num % i == 0):
            greatest_common_divisor = i
    return greatest_common_divisor

def rotate(array: list, k: int) -> None:
    length = len(array)
    k_real = k % length
    key = get_greatest_common_divisor(length, k_real)
    print(length, k_real, key)
    while key:
        index_start = (length - 1 - (key -1))%length
        temp = array[index_start]
        index_cur = index_start
        index_next = (index_cur - k_real)%length
        
        print(index_start, index_cur, index_next)
        while index_next != index_start:
            array[index_cur] = array[index_next]
            print("  ", index_cur, index_next)
            index_cur = index_next
            index_next = (index_cur - k_real)%length
            
        array[index_cur] = temp
        print(" ", array)
        key = key - 1
        

rotate(array, 2)
print(array)
    
    

7 2 1
6 6 4
   6 4
   4 2
   2 0
   0 5
   5 3
   3 1
  [6 7 1 2 3 4 5]
[6 7 1 2 3 4 5]
